import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add font weights you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "CCANDC",
  description: "Generated by CCANDC",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={beVietnamPro.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
